#!/bin/sh

#  faithPD.R
#  
#
#  Created by Dave Jacobson on 12/21/18.
#  
args <- commandArgs(TRUE)
suppressMessages(library(ape))
suppressMessages(library(picante))
suppressMessages(library(ggplot2))
suppressMessages(library(ggtree))
suppressMessages(library(reshape2))
suppressMessages(library(ggstance))
suppressMessages(library(RColorBrewer))

#kruskal.test(filename[i,] ~ 

inTree <- read.tree(args[1])
inFile <- read.table(args[3], header =T, sep = "\t", row.names =1)

pd(t(inFile), inTree, include.root = F) -> faith_pd

row.names(faith_pd) -> sampsPD
for (i in 1:length(row.names(faith_pd))){
    if(grepl("bftm",sampsPD[i]) == TRUE){
        faith_pd$pop[i] <- "bftm"
    } else if (grepl("Ita", sampsPD[i]) == TRUE){
        faith_pd$pop[i] <- "italy"
    } else if (grepl("Had", sampsPD[i]) == TRUE){
        faith_pd$pop[i] <- "hadza"
    } else if (grepl("Ind", sampsPD[i]) == TRUE){
        faith_pd$pop[i] <- "euro"
    } else if (grepl("SRR399", sampsPD[i]) == TRUE){
        faith_pd$pop[i] <- "mongolia"
    } else if (grepl("NO", sampsPD[i]) == TRUE){
        faith_pd$pop[i] <- "norman"
    } else if (grepl("SM", sampsPD[i]) == TRUE){
        faith_pd$pop[i] <- "matses"
    }
}
pathway <- args[2]
name <- args[4]
boxGG <- ggplot(faith_pd, mapping = aes(x = faith_pd$pop, y = faith_pd$PD))
boxGG + geom_boxplot() + ggtitle(pathway, name)
ggsave(paste0(args[2], "_pd.png"), width = 10, height = 6)

### The code below generates a tree using the taxa contributing to each function
### In brief, it uses the relative abundance output from humann2 - where the relative abundance is the relative abundance of the pathway contributed from that specific species across all pathways. So each pathway doesn't add up to 1, rather all pathways together with all species will sum to 1.
### In the tree, the tip labels are generated by determing, for each taxa, which population has the greatest relative abundance. Basically, determining which taxa are important for that pathway in each population.
### The stacked barplot takes that data and expresses the relative abunance for each population. I'm a bit worried that it appears skewed towards mongolia and europe. Not sure if its a read depth, database bias issue, or a biological trend.
length(row.names(inFile)) -> totalTax
length(colnames(inFile)) -> totalSamp
hadLen <- length(grep("TRUE",grepl("Had", colnames(inFile))))
bftmLen <- length(grep("TRUE",grepl("bftm", colnames(inFile))))
itaLen <- length(grep("TRUE",grepl("Ita", colnames(inFile))))
monLen <- length(grep("TRUE",grepl("SRR399", colnames(inFile))))
euroLen <- length(grep("TRUE",grepl("Ind", colnames(inFile))))
normanLen <- length(grep("TRUE",grepl("NO", colnames(inFile))))
matsesLen <- length(grep("TRUE",grepl("SM", colnames(inFile))))
finalMat <- matrix(ncol = 2, nrow = totalTax)
meanMat <- matrix(ncol  = 8, nrow = totalTax)
for (j in 1:totalTax){
    row.names(inFile)[j] -> taxon
    meanMat[j,1] <- taxon
    holder <- numeric(length = 1000)
    for (i in 1:totalSamp){
        if(grepl("Had", colnames(inFile)[i]) == "TRUE"){
            inFile[j,i] -> holder[i]
        }
    }
    sum(holder)/hadLen -> Had
    meanMat[j,2] <- Had
    holder <- numeric(length = 1000)
    for (i in 1:totalSamp){
        if(grepl("bftm", colnames(inFile)[i]) == "TRUE"){
            inFile[j,i] -> holder[i]
        }
    }
    sum(holder)/bftmLen -> BFTM
    meanMat[j,3] <- BFTM
    holder <- numeric(length = 1000)
    for (i in 1:totalSamp){
        if(grepl("Ita", colnames(inFile)[i]) == "TRUE"){
            inFile[j,i] -> holder[i]
        }
    }
    sum(holder)/itaLen -> Ita
    meanMat[j,4] <- Ita
    holder <- numeric(length = 1000)
    for (i in 1:totalSamp){
        if(grepl("Ind", colnames(inFile)[i]) == "TRUE"){
            inFile[j,i] -> holder[i]
        }
    }
    sum(holder)/euroLen -> Euro
    meanMat[j,5] <- Euro
    holder <- numeric(length = 1000)
    for (i in 1:totalSamp){
        if(grepl("SRR399", colnames(inFile)[i]) == "TRUE"){
            inFile[j,i] -> holder[i]
        }
    }
    sum(holder)/monLen -> Mongolia
    meanMat[j,6] <- Mongolia
    holder <- numeric(length = 1000)
    for (i in 1:totalSamp){
        if(grepl("SM", colnames(inFile)[i]) == "TRUE"){
            inFile[j,i] -> holder[i]
        }
    }
    sum(holder)/matsesLen -> Matses
    meanMat[j,7] <- Matses
    holder <- numeric(length = 1000)
    for (i in 1:totalSamp){
        if(grepl("NO", colnames(inFile)[i]) == "TRUE"){
            inFile[j,i] -> holder[i]
        }
    }
    sum(holder)/normanLen -> Norman
    meanMat[j,8] <- Norman
    
    max(c(BFTM, Had, Ita, Euro, Mongolia, Matses, Norman)) -> Max
    matrix(ncol=2, nrow=1) -> tipMatrix
    tipMatrix[1,1] <- taxon
    
    if(Max == Had){
        tipMatrix[1,2] <- "hadza"
    }
    
    if (Max == BFTM){
        tipMatrix[1,2] <- "bftm"
    }
    
    if (Max == Ita){
        tipMatrix[1,2] <- "italy"
    }
    
    if (Max == Euro){
        tipMatrix[1,2] <- "euro"
    }
    
    if (Max == Mongolia){
        tipMatrix[1,2] <- "mongolia"
    }
    if (Max == Matses){
        tipMatrix[1,2] <- "matses"
    }
    if (Max == Norman){
        tipMatrix[1,2] <- "norman"
    }
    
    tipMatrix -> finalMat[j,]
}
colnames(finalMat) <- c("Taxon", "Pop")
as.data.frame(finalMat) -> tipDF
if(any(grepl("Methano", inTree$tip.label)) == TRUE){
grep("TRUE",grepl("Methano", inTree$tip.label))[1]  -> methanoIndex
inTree$tip.label[methanoIndex] -> methanoSpecies
root.phylo(inTree, outgroup = methanoSpecies) -> rootedTree
p <- ggtree(rootedTree)
pLab <- p %<+% tipDF + geom_tippoint(aes(color = Pop), size = 1) + scale_colour_manual(values = c(bftm ="darkblue", euro = "#fdbf6f", hadza = "darkviolet", italy = "#ff7f00", mongolia = "gray54", norman = "#e31a1c", matses = "cornflowerblue")) + geom_tiplab(size =1)

pLab + theme(legend.position = "right")
ggsave(paste0(args[2], "_tree.png"), width = 10, height = 6)
as.data.frame(meanMat) -> meanDF
rootedTree$tip.label -> rootTax
test <- matrix(ncol = 8, nrow = length(rootTax))
for ( i in 1:length(rootTax)){
    as.character(meanDF[grep(rootTax[i], meanDF$V1),1]) -> test[i,1]
    as.character(meanDF[grep(rootTax[i], meanDF$V1),2]) -> test[i,2]
    as.character(meanDF[grep(rootTax[i], meanDF$V1),3]) -> test[i,3]
    as.character(meanDF[grep(rootTax[i], meanDF$V1),4]) -> test[i,4]
    as.character(meanDF[grep(rootTax[i], meanDF$V1),5]) -> test[i,5]
    as.character(meanDF[grep(rootTax[i], meanDF$V1),6]) -> test[i,6]
    as.character(meanDF[grep(rootTax[i], meanDF$V1),7]) -> test[i,7]
    as.character(meanDF[grep(rootTax[i], meanDF$V1),8]) -> test[i,8]
}
as.data.frame(test) -> orderedDF
colnames(orderedDF) <- c("taxa", "hadza", "bftm","italy", "euro", "mongolia", "matses", "norman")
melt(data = orderedDF, id = "taxa") -> meltedOrder
facet_plot(pLab, panel = "stack", data = meltedOrder, geom = geom_barh, mapping = aes(x = as.numeric(value), fill = variable), stat = "identity") + scale_fill_manual(values = c(bftm ="darkblue", euro = "#fdbf6f", hadza = "darkviolet", italy = "#ff7f00", mongolia = "gray54", norman = "#e31a1c", matses = "cornflowerblue")) + theme(legend.position = "right")

ggsave(paste0(args[2], "_bar+tree.png"), width = 10, height = 6)
} else {
    p <- ggtree(inTree)
    pLab <- p %<+% tipDF + geom_tippoint(aes(color = Pop), size = 1) + scale_colour_manual(values = c(bftm ="darkblue", euro = "#fdbf6f", hadza = "darkviolet", italy = "#ff7f00", mongolia = "gray54", norman = "#e31a1c", matses = "cornflowerblue")) + geom_tiplab(size = 1)
    pLab + theme(legend.position = "right")
    ggsave(paste0(args[2], "_tree.png"), width = 10, height = 6)
    as.data.frame(meanMat) -> meanDF
    inTree$tip.label -> inTax
    test <- matrix(ncol = 8, nrow = length(inTax))
    for ( i in 1:length(inTax)){
        as.character(meanDF[grep(inTax[i], meanDF$V1),1]) -> test[i,1]
        as.character(meanDF[grep(inTax[i], meanDF$V1),2]) -> test[i,2]
        as.character(meanDF[grep(inTax[i], meanDF$V1),3]) -> test[i,3]
        as.character(meanDF[grep(inTax[i], meanDF$V1),4]) -> test[i,4]
        as.character(meanDF[grep(inTax[i], meanDF$V1),5]) -> test[i,5]
        as.character(meanDF[grep(inTax[i], meanDF$V1),6]) -> test[i,6]
        as.character(meanDF[grep(inTax[i], meanDF$V1),7]) -> test[i,7]
        as.character(meanDF[grep(inTax[i], meanDF$V1),8]) -> test[i,8]
    }
    as.data.frame(test) -> orderedDF
    colnames(orderedDF) <- c("taxa", "hadza", "bftm","italy", "euro", "mongolia", "matses", "norman")
    melt(data = orderedDF, id = "taxa") -> meltedOrder
    facet_plot(pLab, panel = "stack", data = meltedOrder, geom = geom_barh, mapping = aes(x = as.numeric(value), fill = variable), stat = "identity")+ scale_fill_manual(values = c(bftm ="darkblue", euro = "#fdbf6f", hadza = "darkviolet", italy = "#ff7f00", mongolia = "gray54", norman = "#e31a1c", matses = "cornflowerblue"))+ theme(legend.position = "right")
    
    ggsave(paste0(args[2], "_bar+tree.png"), width = 10, height = 6)
}


